dependencies:
  - python=3.6.7
  - openssl=1.0.2l=0
  - pandas=0.22.0
  - numpy=1.14.0
  - pytz=2017.2
  - scikit-learn=0.19.2
  - scipy=1.0.0
  - setuptools=27.2.0
  - six=1.10.0
  - wheel=0.29.0
  - h5py=2.7.0
  - theano=1.0.1
  - pip:  
    - keras==2.2.0
    - pipeline-runtime==1.0.8
