dependencies:
  - openssl=1.0.2l=0
  - pandas=0.22.0
  - numpy=1.14.0
  - pip=9.0.1
  - python=3.6.1=2
  - pytz=2017.2
  - scikit-learn=0.19.1
  - scipy=1.0.0
  - setuptools=27.2.0
  - six=1.10.0
  - wheel=0.29.0
  - h5py=2.7.0
  - theano=1.0.1
  - pip:  
    - keras==2.1.3
    - pipeline-runtime==1.0.8
