dependencies:
  - python=3.6
  - pip:
    - grpcio>=1.0
    - tensorflow==1.9.0
    - tensorboard==1.9.0
    - pipeline-runtime==1.0.8
    - google-api-python-client>=1.6.7
    - psutil>=5.4.3
    - py-cpuinfo>=3.3.0
    - google-cloud-bigquery>=0.31.0
    - cloud-tpu-profiler>=1.6.0
