dependencies:
  - python=3.6
  - openssl>=1.0.2l=0
  - pandas>=0.22.0
  - numpy>=1.14.0
  - pytz>=2017.2
  - scikit-learn>=0.19.2
  - scipy>=1.0.0
  - sixi>=1.10.0
  - h5py>=2.7.0
  - pip:  
    - keras==2.2.0
    - tensorflow==1.9.0
    - tensorboard==1.9.0
    - pipeline-runtime==1.0.8
