channels:
  - conda-forge 
dependencies:
  - python=3.6
  - numpy=1.14
  - pip:
    - pipeline-runtime==1.0.8
    - mxnet==1.2.1
    - keras==2.2.1
    - tensorflow==1.9.0
    - keras-mxnet==2.2.1
#    - mxnet-model-server==0.4
# Make sure you run pipeline_setup.sh to install protobuf (ONNX models only)
